import './globals.css'
import { Inter } from 'next/font/google';
import Navbar from './components/Navbar';

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${inter.className} overflow-hidden`}>
        <Navbar />
        <div className="absolute -bottom-10 -right-12 h-40 w-40 bg-yellow-100 rounded-3xl"></div>
        {children}
        <div className="absolute -bottom-10 -left-12 h-40 w-40 bg-blue-100 rounded-3xl"></div>
        </body>
    </html>
  )
}
